# Generated by Django 5.2.7 on 2025-10-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение (будет автоматически загружено на Cloudinary)', null=True, upload_to='products/temp/', verbose_name='Загрузить файл'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Вставьте прямую ссылку на изображение', max_length=500, verbose_name='Или вставьте URL'),
        ),
    ]
