# Generated by Django 5.2.7 on 2025-10-26 01:00

import catalog.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=catalog.fields.CloudinaryImageField(upload_to='products/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
